name: Build QMK firmware
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - milo.json
    steps:
    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
    - name: Checkout Userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}

    - name: Build Firmware
      run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}"

    - name: Archive Firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        path: |
          *.hex
          *.bin
          *.uf2