name: Build QMK firmware
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        file:
        - undertow.json
    steps:
    - name: Disable git safe directory
      run : git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v4
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
    - name: Checkout userspace
      uses: actions/checkout@v4
      with:
        path: users/${{ github.actor }}
    - name: Build firmware
      run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}"
    - name: Archive Firmware
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: firmware
        path: |
          *.hex
          *.bin
          *.uf2
