name: Build QMK firmware

on: [push, workflow_dispatch]

env:
  dragon_path: qmk_firmware/keyboards/nullbitsco/tidbit/keymaps/dragonpad/

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - name: Disable git safe directory
      run : git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v7
      with:
        repository: jaygreco/qmk_firmware
        ref: rp2040_clean
        submodules: recursive
    - name: Checkout userspace
      uses: actions/checkout@v7
      with:
        path: users/${{ github.actor }}
    - name: Build firmware
      run: |
        mkdir -p $dragon_path
        cp users/${{ github.actor }}/*.* $dragon_path
        qmk compile -kb nullbitsco/tidbit/rp2040 -km dragonpad

    - name: Archive Firmware
      uses: actions/upload-artifact@v7
      continue-on-error: true
      with:
        name: firmware
        path: |
          *.hex
          *.bin
          *.uf2
